[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "google-generativeai>=0.8.5",
    "langchain-google-genai>=2.0.10",
    "langchain-groq>=0.3.2",
    "langchain-openai>=0.3.18",
    "mcp-use>=1.3.0",
]
